name: C++ Build and Test (GoogleTest)

on:
  push:
    branches:
      - 'feature/*'
      - 'devops/*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # если используешь субмодули
      - name: Init and update submodules
        run: git submodule update --init --recursive
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Build GoogleTest
        run: |
          mkdir -p googletest/build
          cd googletest/build
          cmake ..
          make -j$(nproc)

      - name: Build and run tests
        run: make test
